package dbmodels

const (
	EXPORT_STATUS_QUEUED   = "queued"
	EXPORT_STATUS_RUNNING  = "running"
	EXPORT_STATUS_COMPLETE = "complete"
	EXPORT_STATUS_FAILED   = "failed"

	EXPORT_TYPE_DATA  = "data"
	EXPORT_TYPE_FILES = "files"
)

var EXPORT_STATUS_VALUES = []string{
	EXPORT_STATUS_QUEUED,
	EXPORT_STATUS_RUNNING,
	EXPORT_STATUS_COMPLETE,
	EXPORT_STATUS_FAILED,
}

var EXPORT_TYPE_VALUES = []string{
	EXPORT_TYPE_DATA,
	EXPORT_TYPE_FILES,
}
