root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
full_bin = "./tmp/musenalm --dir ./pb_data serve"
cmd = "go build -tags=dev,fts5 -o ./tmp/musenalm ."
delay = 400
exclude_dir = [
	"views/assets",
	"views/node_modules",
	"tmp",
	"vendor",
	"testdata",
	"data_git",
	"cache_gnd",
	"cache_geonames",
	"pb_data",
	"Almanach-Bilder",
	"Static-Bilder",
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "gohtml", "js", "css", "xsl"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = ["npm --prefix views/ run build"]
rerun = false
rerun_delay = 250
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[proxy]
app_port = 8090
enabled = true
proxy_port = 8081

[screen]
clear_on_rebuild = true
keep_scroll = true
