services:
  musenalm:
    build: .
    expose:
      - "8090"
    volumes:
      - musenalm:/app/data
    networks:
      - caddynet

volumes:
  musenalm:
    external: true

networks:
  caddynet:
    external: true
