package models

var EDITORSTATE_VALUES = []string{"Unknown", "Inspected", "Partially Edited", "Waiting", "Edited"}

var MEDIA_TYPE_VALUES = []string{
	"audio",
	"Mikroform",
	"Computermedien",
	"mikroskopisch",
	"projizierbar",
	"stereografisch",
	"ohne Hilfsmittel",
	"video",
}

var CARRIER_TYPE_VALUES = []string{
	"Tonträger",
	"Audiocartridge",
	"Phonographenzylinder",
	"Audiodisk",
	"Tonspurspule",
	"Notenrolle",
	"Audiokassette",
	"Tonbandspule",
	"Datenträger",
	"Speicherkarte",
	"Computerchip-Cartridge",
	"Computerdisk",
	"Computerdisk-Cartridge",
	"Magnetbandcartridge",
	"Magnetbandkassette",
	"Magnetbandspule",
	"Online-Ressource",
	"Datenträger für Mikroformen",
	"Mikrofilmlochkarte",
	"Mikrofiche",
	"Mikrofichekassette",
	"Mikrofilm-Cartridge",
	"Mikrofilmkassette",
	"Mikrofilmspule",
	"Mikrofilmstreifen",
	"Lichtundurchlässiger Mikrofiche",
	"Trägermedien für Mikroskop-Anwendungen",
	"Objektträger",
	"Datenträger von projizierbaren Bildern",
	"Filmdose",
	"Filmkassette",
	"Filmspule",
	"Filmstreifen",
	"Filmstreifen für Einzelbildvorführung",
	"Filmstreifen-Cartridge",
	"Overheadfolie",
	"Dia",
	"Stereografische Datenträger",
	"Stereobild",
	"Stereografische Disk",
	"Datenträger, die ohne Hilfsmittel zu benutzen sind",
	"Karte",
	"Flipchart",
	"Rolle",
	"Blatt",
	"Band",
	"Video-Datenträger",
	"Videocartridge",
	"Videokassette",
	"Videobandspule",
	"Mikrofilmrolle",
	"Gegenstand",
	"Videodisk",
	"Filmrolle",
	"Audio Belt",
	"Audio wire reel",
}
var LANGUAGE_VALUES = []string{
	"abk",
	"aar",
	"afr",
	"aka",
	"alb",
	"amh",
	"ara",
	"arg",
	"arm",
	"asm",
	"ava",
	"ave",
	"aym",
	"aze",
	"bam",
	"bak",
	"baq",
	"bel",
	"ben",
	"bis",
	"bos",
	"bre",
	"bul",
	"bur",
	"cat",
	"cha",
	"che",
	"nya",
	"chi",
	"chu",
	"chv",
	"cor",
	"cos",
	"cre",
	"hrv",
	"cze",
	"dan",
	"div",
	"dut",
	"dzo",
	"eng",
	"epo",
	"est",
	"ewe",
	"fao",
	"fij",
	"fin",
	"fre",
	"fry",
	"ful",
	"gla",
	"glg",
	"lug",
	"geo",
	"ger",
	"gre",
	"kal",
	"grn",
	"guj",
	"hat",
	"hau",
	"heb",
	"her",
	"hin",
	"hmo",
	"hun",
	"ice",
	"ido",
	"ibo",
	"ind",
	"ina",
	"ile",
	"iku",
	"ipk",
	"gle",
	"ita",
	"jpn",
	"jav",
	"kan",
	"kau",
	"kas",
	"kaz",
	"khm",
	"kik",
	"kin",
	"kir",
	"kom",
	"kon",
	"kor",
	"kua",
	"kur",
	"lao",
	"lat",
	"lav",
	"lim",
	"lin",
	"lit",
	"lub",
	"ltz",
	"mac",
	"mlg",
	"may",
	"mal",
	"mlt",
	"glv",
	"mao",
	"mar",
	"mah",
	"mon",
	"nau",
	"nav",
	"nde",
	"nbl",
	"ndo",
	"nep",
	"nor",
	"nob",
	"nno",
	"oci",
	"oji",
	"ori",
	"orm",
	"oss",
	"pli",
	"pus",
	"per",
	"pol",
	"por",
	"pan",
	"que",
	"rum",
	"roh",
	"run",
	"rus",
	"sme",
	"smo",
	"sag",
	"san",
	"srd",
	"srp",
	"sna",
	"snd",
	"sin",
	"slo",
	"slv",
	"som",
	"sot",
	"spa",
	"sun",
	"swa",
	"ssw",
	"swe",
	"tgl",
	"tah",
	"tgk",
	"tam",
	"tat",
	"tel",
	"tha",
	"tib",
	"tir",
	"ton",
	"tso",
	"tsn",
	"tur",
	"tuk",
	"twi",
	"uig",
	"ukr",
	"urd",
	"uzb",
	"ven",
	"vie",
	"vol",
	"wln",
	"wel",
	"wol",
	"xho",
	"iii",
	"yid",
	"yor",
	"zha",
	"zul",
}

var CONTENT_TYPE_VALUES = []string{
	"kartografisches Daten-Set",
	"kartografisches Bild",
	"kartografisches Bewegtbild",
	"kartografisches taktiles Bild",
	"kartografische taktile dreidimensionale Form",
	"kartografische dreidimensionale Form",
	"Computerdaten",
	"Computerprogramm",
	"Bewegungsnotation",
	"Noten",
	"aufgeführte Musik",
	"Geräusche",
	"gesprochenes Wort",
	"unbewegtes Bild",
	"taktiles Bild",
	"taktile Noten",
	"taktile Bewegungsnotation",
	"taktiler Text",
	"taktile dreidimensionale Form",
	"Text",
	"dreidimensionale Form",
	"dreidimensionales Bewegtbild",
	"zweidimensionales Bewegtbild",
	"aufgeführte Bewegung",
}

var MUSENALM_STATUS_VALUES = []string{
	"Original vorhanden",
	"Reprint vorhanden",
	"Fremde Herkunft",
}

var MUSENALM_TYPE_VALUES = []string{
	"Corrigenda",
	"Diagramm",
	"Gedicht/Lied",
	"Graphik",
	"Graphik-Verzeichnis",
	"graph. Anleitung",
	"graph. Strickanleitung",
	"graph. Tanzanleitung",
	"Inhaltsverzeichnis",
	"Kalendarium",
	"Karte",
	"Musikbeigabe",
	"Musikbeigaben-Verzeichnis",
	"Motto",
	"Prosa",
	"Rätsel",
	"Sammlung",
	"Spiegel",
	"szen. Darstellung",
	"Tabelle",
	"Tafel",
	"Titel",
	"Text",
	"Trinkspruch",
	"Umschlag",
	"Widmung",
}

var MUSENALM_PAGINATION_VALUES = []string{
	"Römische Seitenzählung",
	"Arabische Seitenzählung",
	"Alphabetische Seitenzählung",
	"Sonstige Seitenzählung",
	"1. Arabische Seitenzählung",
	"2. Arabische Seitenzählung",
	"3. Arabische Seitenzählung",
	"4. Arabische Seitenzählung",
	"5. Arabische Seitenzählung",
	"6. Arabische Seitenzählung",
	"7. Arabische Seitenzählung",
	"8. Arabische Seitenzählung",
	"1. Römische Seitenzählung",
	"2. Römische Seitenzählung",
	"3. Römische Seitenzählung",
	"4. Römische Seitenzählung",
	"5. Römische Seitenzählung",
	"6. Römische Seitenzählung",
	"7. Römische Seitenzählung",
	"8. Römische Seitenzählung",
}

var MUSENALM_MIME_TYPES = []string{
	"application/pdf",
	"image/png",
	"image/vnd.mozilla.apng",
	"image/jpeg",
	"image/jp2",
	"image/jpx",
	"image/jpm",
	"image/gif",
	"image/jxs",
	"image/jxl",
	"image/x-xpixmap",
	"image/vnd.adobe.photoshop",
	"image/webp",
	"image/tiff",
	"image/bmp",
	"image/x-icon",
	"image/vnd.djvu",
	"image/bpg",
	"image/vnd.dwg",
	"image/x-icns",
	"image/heic",
	"image/heic-sequence",
	"image/heif",
	"image/heif-sequence",
	"image/vnd.radiance",
	"image/x-xcf",
	"image/x-gimp-pat",
	"image/x-gimp-gbr",
	"image/avif",
	"image/jxr",
	"image/svg+xml",
}

const (
	PLACES_TABLE  = "places"
	AGENTS_TABLE  = "agents"
	SERIES_TABLE  = "series"
	ENTRIES_TABLE = "entries"
	ITEMS_TABLE   = "items"

	ANNOTATION_FIELD = "annotation"

	MUSENALMID_FIELD = "musenalm_id"
	EDITSTATE_FIELD  = "edit_state"
	COMMENT_FIELD    = "edit_comment"
)
